// Generated by lighting/gi/generate_fragment.py.
// Shared storage ABI for native raster fragments, RT and history.
struct GIRecord {
	vec4 position; // world xyz, raster footprint
	uvec4 identity; // surface + 1, primitive and side, geometry generation, next + 1
	uvec4 geometry; // oct shading normal, oct geometric normal, pixel including eye, flags
	vec4 raw; // unfiltered frame mean, changed/invalid
};
uint gi_pack_normal(vec3 n) {
	n /= abs(n.x)+abs(n.y)+abs(n.z);
	vec2 p = n.z >= 0.0 ? n.xy : (1.0-abs(n.yx))*mix(vec2(-1.0),vec2(1.0),greaterThanEqual(n.xy,vec2(0.0)));
	return packSnorm2x16(p);
}
vec3 gi_unpack_normal(uint packed) {
	vec2 p=unpackSnorm2x16(packed);
	vec3 n=vec3(p,1.0-abs(p.x)-abs(p.y));
	float t=max(-n.z,0.0);
	n.xy+=mix(vec2(t),vec2(-t),greaterThanEqual(n.xy,vec2(0.0)));
	return normalize(n);
}
bool gi_same_side(GIRecord a,GIRecord b) {
	return a.identity.x==b.identity.x && (a.identity.y&1u)==(b.identity.y&1u) &&
		dot(gi_unpack_normal(a.geometry.y),gi_unpack_normal(b.geometry.y))>0.95;
}
layout(constant_id=3) const bool gi_gather_pass=false;
layout(set=4,binding=0,std140) uniform RasterGI { uvec4 size_capacity; vec4 diagnostic; } gi_raster;
layout(set=4,binding=1,std430) buffer GIAllocator { uint count; uint overflow; uint missing; uint lookups; uvec4 details[]; } gi_allocator;
layout(set=4,binding=2,std430) buffer GIHeads { uint head[]; } gi_heads;
layout(set=4,binding=3,std430) buffer GIRecords { GIRecord record[]; } gi_records;
layout(set=4,binding=4,std430) readonly buffer GIRevisions { uvec4 value[]; } gi_revisions;
layout(set=4,binding=5,std430) readonly buffer GILight { vec4 value[]; } gi_light;
void gi_gather_surface(vec3 position,vec3 normal,vec3 geometric,vec3 albedo,float footprint,uint surface,uint primitive,int eye,bool transparent) {
	if (surface==0u || any(isnan(position)) || any(isnan(normal))) { atomicAdd(gi_allocator.missing,1u); return; }
	uint index=atomicAdd(gi_allocator.count,1u);
	if (index>=gi_raster.size_capacity.w) { atomicAdd(gi_allocator.overflow,1u); return; }
	uvec2 pixel=uvec2(gl_FragCoord.xy);
	uint address=pixel.x+gi_raster.size_capacity.x*(pixel.y+uint(eye)*gi_raster.size_capacity.y);
	GIRecord item;
	item.position=vec4(position,footprint);
	item.identity=uvec4(surface,primitive,gi_revisions.value[surface-1u].w,atomicExchange(gi_heads.head[address],index+1u));
	item.geometry=uvec4(gi_pack_normal(normal),gi_pack_normal(geometric),address,uint(transparent));
	item.raw=vec4(0.0);
	gi_records.record[index]=item;
}
vec3 gi_raster_irradiance(uint surface,uint primitive,vec3 position,int eye) {
	if (gi_raster.diagnostic.w>0.0) { return gi_raster.diagnostic.rgb; }
	uvec2 pixel=uvec2(gl_FragCoord.xy);
	if (gi_raster.size_capacity.z==0u) { return vec3(0.0); }
	uint address=pixel.x+gi_raster.size_capacity.x*(pixel.y+uint(eye)*gi_raster.size_capacity.y);
	atomicAdd(gi_allocator.lookups,1u);
	uint entry=gi_heads.head[address];
	while (entry!=0u) {
		GIRecord item=gi_records.record[entry-1u];
		if (item.identity.x==surface && item.identity.y==primitive) {
			return gi_light.value[entry-1u].rgb;
		}
		entry=item.identity.w;
	}
	uint missed=atomicAdd(gi_allocator.missing,1u);
	if (missed<16u) {
		uint first=gi_heads.head[address];
		GIRecord candidate=gi_records.record[first==0u ? 0u : first-1u];
		gi_allocator.details[missed*3u]=uvec4(surface,primitive,pixel);
		gi_allocator.details[missed*3u+1u]=uvec4(floatBitsToUint(position),first);
		gi_allocator.details[missed*3u+2u]=uvec4(candidate.identity.xy,floatBitsToUint(distance(candidate.position.xyz,position)),floatBitsToUint(candidate.position.w));
	}
	// Missing coverage is an error, never a second estimator or an invisible black fallback.
	return vec3(1.0,0.0,1.0);
}
